POST http://localhost:9998/products
content-type: application/json

{
  "name" : "Bolsinha de Vaquinha",
  "price": 17.6
}

###

GET http://localhost:9998/products

###

GET http://localhost:9998/products/a6b5019c-5c66-4532-be89-b0c1aead15e1
###

PUT  http://localhost:9998/products/de1dfc92-9d5e-4307-836b-772507958707
content-type: application/json

{
  "name" : "Caderno 96 Folhas Barbie",
  "price": 25
}

###

DELETE  http://localhost:9998/products/de1dfc92-9d5e-4307-836b-772507958707