POST http://localhost:9998/products
content-type: application/json

{
  "name" : "Borracha de gatinho",
  "price": 6.6
}

###

GET http://localhost:9998/products

###

GET http://localhost:9998/products/9498f3d7-76af-4084-84d0-96cab6e3db5b
###

PUT  http://localhost:9998/products/88ea27ba-f98a-4ee6-9558-235e9a3cf625
content-type: application/json

{
  "name" : "Caderno 96 Folhas Barbie",
  "price": 25
}

###

DELETE  http://localhost:9998/products/9498f3d7-76af-4084-84d0-96cab6e3db5b